name: CI

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - '*.md'
      - '*.ignore'
      - LICENSE
  
  workflow_dispatch:

jobs:
  
  RNAseq_PREPROCESS_CI_TESTS:
    
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: INSTALL-NEXTFLOW
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/

      # Test via docker
      - name: TEST-DOCKER_ALL
        run: |
          NXF_VER=21.10.6 nextflow run main.nf -profile docker,test_with_new_idx,test_resources --only_idx
          NXF_VER=21.10.6 nextflow run main.nf -profile docker,test_with_existing_idx,test_resources --only_fastqc
          NXF_VER=21.10.6 nextflow run main.nf -profile docker,test_with_existing_idx,test_resources --skip_fastqc
          NXF_VER=21.10.6 nextflow run main.nf -profile docker,test_with_existing_idx,test_resources --skip_tximport
          NXF_VER=21.10.6 nextflow run main.nf -profile docker,test_with_existing_idx,test_resources
          NXF_VER=21.10.6 nextflow run main.nf -profile docker,test_with_existing_idx,test_resources --trim_reads --trim_length 50

      # Write software versions and command lines to the misc folder
      - name: Commit software versions
        run: |
          git config --global user.name 'atpoint'
          git config --global user.email 'atpoint@users.noreply.github.com'
          mkdir -p misc && cp rnaseq_preprocess_results/pipeline_info/*.txt misc/
          git add misc/*.txt
          if (( $(git status -s | grep -c 'misc/') > 0 )); then 
            git commit -am "update software version and command line reports"
            git push -f
          fi
          
