name: CI

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - '*.md'
      - '*.ignore'
      - LICENSE
  pull_request:
    branches:
      - '**'

  workflow_dispatch:

jobs:
  
  RNAseq_PREPROCESS_CI_TESTS:
    
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: INSTALL-NEXTFLOW
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/

      - name: TEST-DOCKER_ALL
        run: |
          # building new index and exit
          NXF_VER=21.10.6 nextflow run main.nf -profile docker,test_with_new_idx,test_resources --only_idx

          # using existing index
          NXF_VER=21.10.6 nextflow run main.nf -profile docker,test_with_existing_idx,test_resources
          NXF_VER=21.10.6 nextflow run main.nf -profile docker,test_with_existing_idx,test_resources --only_fastqc
          NXF_VER=21.10.6 nextflow run main.nf -profile docker,test_with_existing_idx,test_resources --skip_fastqc
          
      - uses: eWaterCycle/setup-singularity@v7
        with:
          singularity-version: 3.8.0
    
      - name: TEST-SINGULARITY
        run: NXF_VER=21.10.6 nextflow run main.nf -profile docker,test_with_existing_idx,test_resources
